" Just in case
set nocompatible

" Set terminal title to "vim:<file>"
set title
autocmd BufEnter * let &titlestring = "vim:" . expand("%:t")

" Highlight chars that go over 100 columns
if exists('+colorcolumn')
  set colorcolumn=101
  highlight ColorColumn ctermbg=red
else
  highlight OverLength ctermbg=red ctermfg=white guibg=#592929
  match OverLength /\%101v.\+/
endif

" Highlight search result
set hlsearch
highlight Search guibg=Yellow guifg=Black ctermbg=Yellow ctermfg=Black

" Automagically remove all trailing whitespace
autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif

" Show relative line numbers except cursor (version >= 7.4)
set relativenumber
set number
set numberwidth=2

" Prettify
syntax enable
filetype plugin indent on
set background=light

" Change leader character
nnoremap <SPACE> <Nop>
let mapleader=" "

" Tabs set at 4 spaces
set tabstop=4 shiftwidth=4 expandtab

" Highlight and make searches case-insensitive
set incsearch
set ignorecase

" New tab
nnoremap <silent> <C-t> :tabnew<CR>

" Next tab
nnoremap <silent> <C-Right> :tabnext<CR>

" Previous tab
nnoremap <silent> <C-Left> :tabprevious<CR>

" Edit vimrc \ev
nnoremap <silent> <Leader>ev :tabnew<CR>:e ~/.vimrc<CR>

let macvim_skip_colorscheme=1

" Pathogen support
execute pathogen#infect()
execute pathogen#helptags()

" Remove annoying brace highlight in vim-cpp-enhanced-highlight
let c_no_curly_error=1

" Vertical indentation line color
let g:indentLine_color_term = 100

" Always show airline statusline
set laststatus=2
